
FROM python:3.9-bullseye

RUN apt-get update && apt-get upgrade -y

RUN pip install --upgrade pip

WORKDIR /domain_based_gene_mining

# COPY requirements.sh requirements.sh

# RUN ./requirements.sh

